alter table cnae2 enable keys;
alter table empresa2 enable keys;
alter table estabelecimento2 enable keys;
alter table motivo_situacao_cadastral2 enable keys;
alter table municipio2 enable keys;
alter table natureza_juridica2 enable keys;
alter table optante_simples2 enable keys;
alter table pais2 enable keys;
alter table qualificacao_socio2 enable keys;
alter table socio2 enable keys;
drop table cnae_old;
drop table empresa_old;
drop table estabelecimento_old;
drop table motivo_situacao_cadastral_old;
drop table municipio_old;
drop table natureza_juridica_old;
drop table optante_simples_old;
drop table pais_old;
drop table qualificacao_socio_old;
drop table socio_old;
RENAME table cnae TO cnae_old, cnae2 TO cnae;
RENAME table empresa TO empresa_old, empresa2 TO empresa;
RENAME table estabelecimento TO estabelecimento_old, estabelecimento2 TO estabelecimento;
RENAME table motivo_situacao_cadastral TO motivo_situacao_cadastral_old, motivo_situacao_cadastral2 TO motivo_situacao_cadastral;
RENAME table municipio TO municipio_old, municipio2 TO municipio;
RENAME table natureza_juridica TO natureza_juridica_old, natureza_juridica2 TO natureza_juridica;
RENAME table optante_simples TO optante_simples_old, optante_simples2 TO optante_simples;
RENAME table pais TO pais_old, pais2 TO pais;
RENAME table qualificacao_socio TO qualificacao_socio_old, qualificacao_socio2 TO qualificacao_socio;
RENAME table socio TO socio_old, socio2 TO socio;